
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew cairo
brew cmake
brew composer
brew ctags
brew curl
brew docker
brew docker-compose
brew docker-machine
brew emacs
brew exif
brew fish
brew fontconfig
brew fontforge
brew freetype
brew fribidi
brew gawk
brew gd
brew gdbm
brew gettext
brew ghq
brew git
brew glib
brew gmp
brew gnu-sed --with-default-names
brew gnutls
brew graphite2
brew harfbuzz
brew icu4c
brew imagemagick
brew jemalloc
brew jpeg
brew libevent
brew libexif
brew libffi
brew libpng
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvterm
brew libxml2
brew libyaml
brew llvm --with-toolchain --with-lldb --with-python@2 --with-polly-gpgpu
brew luajit
brew mas
brew mcrypt
brew mhash
brew mpfr
brew msgpack
brew mysql
brew neovim
brew nettle
brew node
brew openssl
brew p11-kit
brew pango
brew pcre
brew pcre2
brew peco
brew phantomjs
brew pixman
brew pkg-config
brew popt
brew pyenv
brew pyenv-virtualenv
brew python@2
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew rtags
brew sqlite
brew ssh-copy-id
brew swig
brew tmux
brew tmux-mem-cpu-load
brew tree
brew unibilium
brew webp
brew xz

tap homebrew/services

tap homebrew/cask
cask alfred
cask evernote
cask google-chrome
cask iterm2
cask pycharm
cask slack

tap argon/mas

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --with-powerline

# Other Cask applications
cask clion
cask google-backup-and-sync
cask hyperswitch
cask java
cask shiftit
cask visual-studio-code

# App Store applications
appstore 539883307 LINE (5.8.0)
appstore 497799835 Xcode (9.4.1)
