
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew cmake
brew composer
brew ctags
brew curl
brew emacs
brew exif
brew fish
brew fontconfig
brew freetype
brew gawk
brew gd
brew gdbm
brew gettext
brew ghq
brew git
brew gmp
brew gnu-sed --with-default-names
brew gnutls
brew icu4c
brew imagemagick
brew jemalloc
brew jpeg
brew libevent
brew libexif
brew libffi
brew libpng
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvterm
brew libxml2
brew llvm --with-toolchain --with-lldb --with-python@2 --with-polly-gpgpu
brew luajit
brew mas
brew mcrypt
brew mhash
brew mpfr
brew msgpack
brew mysql
brew neovim
brew nettle
brew node
brew openssl
brew p11-kit
brew pcre
brew pcre2
brew peco
brew phantomjs
brew pkg-config
brew popt
brew pyenv
brew pyenv-virtualenv
brew python@2
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew rtags
brew sqlite
brew swig
brew tmux
brew tmux-mem-cpu-load
brew tree
brew unibilium
brew webp
brew xz

tap homebrew/services

tap homebrew/cask
cask alfred
cask google-backup-and-sync
cask iterm2
cask shiftit

tap argon/mas

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew ricty --with-powerline

# Other Cask applications
cask google-chrome
cask hyperswitch
cask java
cask slack
