# cmake completion
[[plugins]]
repo = 'deoplete-plugins/deoplete-clang'
on_ft = ['cmake']
hook_add = '''
    let g:deoplete#sources#clang#libclang_path="/usr/local/llvm-7.0/lib/libclang.so"
    let g:deoplete#sources#clang#clang_header="/usr/local/llvm-7.0/lib/clang"
'''

# moving header and source
[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['c', 'cpp']
hook_source = '''
    nmap <silent> <leader>aa :A<CR>
    nmap <silent> <leader>at :AT<CR>
    nmap <silent> <leader>av :AV<CR>
'''

# cmake plugin
[[plugins]]
repo = 'vhdirk/vim-cmake'
on_ft = ['c', 'cpp', 'cmake']
hook_source = '''
'''

# Doxygen
[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'
on_ft = ['c', 'cpp']
hook_source = '''
    nmap <C-_> :Dox<CR>
'''
