[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    " 行の最初の文字の前にコメント文字をトグル
    nmap <Leader><Leader> <Plug>(caw:hatpos:toggle)
    vmap <Leader><Leader> <Plug>(caw:hatpos:toggle)
    " 行頭にコメントを挿入
    nmap <Leader>g<leader> <Plug>(caw:hatpos:comment)
    vmap <Leader>g<leader> <Plug>(caw:hatpos:comment)
'''

[[plugins]]
repo = 'yggdroot/indentline'
hook_add = '''
    set list lcs=tab:\|\
'''

[[plugins]]
repo = 'rakr/vim-one'
hook_add = '''
    let g:one_allow_italics = 1
'''

# [[plugins]]
# repo = 'w0ng/vim-hybrid'
# 
# [[plugins]]
# repo = 'ayu-theme/ayu-vim'
# hook_add = '''
#     let ayucolor='dark'
#     let g:indentLine_showFirstIndentLevel = 1
#     let g:indentLine_setColors = 0
# '''


[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merge = '0'
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/plugins/coc.rc.vim
'''
hook_source = '''
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
    let g:polyglot_disabled = ['jsx', 'latex', 'tsx', 'javascript', 'typescript', 'javascriptreact', 'typescriptreact']
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    set noshowmode

    function! NearestMethodOrFunction() abort
        return get(b:, 'vista_nearest_method_or_function', '')
    endfunction
    function! CocCurrentFunction() abort
        return get(b:, 'coc_current_function', '')
    endfunction

    let g:lightline = {
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ],
        \             [ 'readonly', 'filename', 'modified' ],
        \             [ 'cocstatus', 'currentfunction', 'gitbranch' ],
        \           ]
        \ },
        \ 'component_function': {
        \   'vista': 'NearestMethodOrFunction',
        \   'cocstatus': 'coc#status',
        \   'currentfunction': 'CocCurrentFunction',
        \   'gitbranch': 'gitbranch#name',
        \ },
        \ 'separator': { 'left': '', 'right': '' },
        \ 'subseparator': { 'left': '', 'right': '' },
        \ }
'''

[[plugins]]
repo = 'itchyny/vim-gitbranch'
depends = 'lightline.vim'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
depends = 'lightline.vim'
hook_add = '''
    set showtabline=2
    let g:lightline#bufferline#show_number = 2
    let g:lightline#bufferline#shorten_path = 1
    let g:lightline#bufferline#unnamed = '[No Name]'
    let g:lightline#bufferline#enable_devicons = 1

    let g:lightline.tabline = {'left': [['buffers']], 'right': [['close']]}
    let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
    let g:lightline.component_type = {'buffers': 'tabsel'}
    nmap <Leader>1 <Plug>lightline#bufferline#go(1)
    nmap <Leader>2 <Plug>lightline#bufferline#go(2)
    nmap <Leader>3 <Plug>lightline#bufferline#go(3)
    nmap <Leader>4 <Plug>lightline#bufferline#go(4)
    nmap <Leader>5 <Plug>lightline#bufferline#go(5)
    nmap <Leader>6 <Plug>lightline#bufferline#go(6)
    nmap <Leader>7 <Plug>lightline#bufferline#go(7)
    nmap <Leader>8 <Plug>lightline#bufferline#go(8)
    nmap <Leader>9 <Plug>lightline#bufferline#go(9)
    nmap <Leader>0 <Plug>lightline#bufferline#go(10)
'''

[[plugins]]
repo = 'shougo/neosnippet-snippets'

[[plugins]]
repo = 'shougo/context_filetype.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja,en
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
hook_add = '''
    let g:defx_icons_column_length = 2
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'


[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
    call submode#enter_with('bufmove', 'n', '', '<C-w>>', '<C-w>>')
    call submode#enter_with('bufmove', 'n', '', '<C-w><', '<C-w><')
    call submode#enter_with('bufmove', 'n', '', '<C-w>+', '<C-w>+')
    call submode#enter_with('bufmove', 'n', '', '<C-w>-', '<C-w>-')
    call submode#map('bufmove', 'n', '', '>', '<C-w>>')
    call submode#map('bufmove', 'n', '', '<', '<C-w><')
    call submode#map('bufmove', 'n', '', '+', '<C-w>+')
    call submode#map('bufmove', 'n', '', '-', '<C-w>-')
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
    set diffopt+=vertical
'''

[[plugins]]
repo = 'deris/vim-shot-f'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    map <Leader>s <Plug>(easymotion-prefix)
'''

[[plugins]]
repo = 'mg979/vim-visual-multi'

[[plugins]]
repo = 'pantharshit00/vim-prisma'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'ianks/vim-tsx'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'towolf/vim-helm'

[[plugins]]
repo = 'martinda/Jenkinsfile-vim-syntax'
