# [[plugins]]
# repo = 'zchee/deoplete-jedi'
# on_ft = ['python']
# hook_add = '''
#     let g:deoplete#sources#jedi#enable_typeinfo = 1
#     autocmd FileType python setlocal completeopt-=preview
# '''

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']
hook_add = '''
    let g:virtualenv_auto_activate = 1
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'heavenshell/vim-pydocstring'
on_ft = ['python']
hook_add = '''
    nmap <silent> <C-_> <Plug>(pydocstring)
'''
