[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
hook_add = '''
    let g:deoplete#sources#jedi#debug_server = 1
    autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
hook_add = '''
    let g:jedi#auto_initialization = 0
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#smart_auto_mappings = 0
    let g:jedi#completions_enabled = 0
    let g:jedi#use_tabs_not_buffer = 1
    let g:jedi#goto_command = "<Leader>rj"
'''

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
on_ft = ['python']
hook_add = '''
    let g:gen_tags#ctags_auto_gen = 1
    let g:gen_tags#gtags_auto_gen = 0
    let g:gen_tags#gtags_default_map = 0
'''

[[plugins]]
repo = 'tpope/vim-dispatch'
on_ft = ['python']

[[plugins]]
repo = 'janko-m/vim-test'
on_ft = ['python']
depends = ['vim-dispatch']
hook_add = '''
    let g:test#strategy = 'dispatch'
'''

[[plugins]]
repo = 'aliev/vim-compiler-python'
on_ft = ['python']
