name: Dotfiles

on:
  push:
    branches:
      - master
  pull_request:
    branchs:
      - master

jobs:
  macos:
    name: macos
    runs-on: macos-latest
    steps:
      - name: Install
        shell: bash
        run: curl -L https://raw.githubusercontent.com/arwtyxouymz/dotfiles/master/install | bash
